#!/bin/bash

#######################################################################################################################
# Library check

function message_fail_libsh()
{
	    local ZENITY_INSTALLED
        ZENITY_INSTALLED=`dpkg-query -l | grep zenity-common |& awk -F" " '{ print $1 }'`

	    if [ "${ZENITY_INSTALLED}" != "ii" ]
	    then
		    echo "Impossible to connect to internet. Please, double check your Internet connection"
	    else
		    zenity --error --text "Impossible to connect to internet. Please, double check your Internet connection"
	    fi
}

if [ ! -d libsh ]
then
	git clone https://github.com/architech-boards/libsh.git
	[ $? -eq 0 ] || { message_fail_libsh; exit 1; }
fi
cd libsh
git pull
[ $? -eq 0 ] || { message_fail_libsh; exit 1; }
source lib.sh
get_sudo_password ${SUDO_PASSWORD}
cd ..

URL_DOWNLOAD=$(get_url_download)

#######################################################################################################################
# Check maintenance

check_maintenance

###########################################################################################################
# Parameters

YOCTO_DIRECTORY="yocto"
cd ..
ROOT_DIRECTORY=`pwd`
BASEROOT_SDK=${ROOT_DIRECTORY}
cd ../..
ARCHITECH_DIRECTORY=`pwd`
cd ${ROOT_DIRECTORY}
NR_CPUS=`grep -c ^processor /proc/cpuinfo`
DEFAULT_MACHINE="ls1021atwr"
WGET_TIMEOUT=60


###########################################################################################################
# Script pre-install

cd $BASEROOT_SDK
wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/ls1021atwr/script/daisy/pre-script.sh
[ $? -eq 0 ] || { internet_error; }
chmod 777 pre-script.sh
./pre-script.sh
rm pre-script.sh

###########################################################################################################
# Yocto installation

cd ${ROOT_DIRECTORY}
mkdir -p ${YOCTO_DIRECTORY}
cd ${YOCTO_DIRECTORY}
if [ ! -d .repo ]
then
    repo init -u https://github.com/architech-boards/ls1021a-manifest.git -b daisy -m manifest.xml > /dev/null 2>&1
    [ $? -eq 0 ] || { rm -rf .repo; internet_error; }
fi
repo sync > /dev/null 2>&1
source poky/fsl-setup-poky -m ls1021atwr

###########################################################################################################
# Script post-install

cd $BASEROOT_SDK
wget --timeout=${WGET_TIMEOUT} ${URL_DOWNLOAD}/ls1021atwr/script/daisy/post-script.sh
[ $? -eq 0 ] || { internet_error; }
chmod 777 post-script.sh
./post-script.sh
rm post-script.sh

exit 0
